#!/bin/bash

CONFIG_ID=$1
INSTANCE_ID=$2
SEED=$3
INSTANCE=$4


shift 4

./bt_main --main::instance "$INSTANCE" \
          --main::method BSA \
          --main::seed "$SEED" \
          --BSA::max_evaluations 500000 \
          --main::irace-enable \
          "$@"